/**
 * ข้อมูลสถานการณ์น้ำ คลอง ถนน และกล้องวงจรปิด (กทม. นนทบุรี ปทุมธานี)
 * ให้ความสำคัญเป็นพิเศษกับโซน: งามวงศ์วาน, ประชาชื่น, แจ้งวัฒนะ, ม.เกษตรศาสตร์
 */

const INITIAL_DATA = {
  // โซนพิเศษที่ปักหมุดไว้ด้านบนสุด
  priorityZones: [
    {
      id: "ngamwongwan",
      name: "โซนงามวงศ์วาน",
      province: "นนทบุรี / กทม.",
      status: "critical", // normal, warning, critical
      statusText: "วิกฤต - มีน้ำท่วมขังรอการระบาย",
      roadFloodLevel: 25, // cm
      roadCondition: "ท่วมช่องทางซ้ายและกลาง 2-3 เลน (ระดับน้ำ 20-25 ซม.) รถเล็กโปรดหลีกเลี่ยง",
      keyLocation: "แยกพงษ์เพชร - หน้าเดอะมอลล์งามวงศ์วาน - ใต้ทางด่วน",
      canalName: "คลองบางเขน (ช่วงงามวงศ์วาน) / คลองเปรมประชากร",
      canalLevel: 1.45, // ม.รทก.
      canalMaxLevel: 1.50,
      canalCapacityPercent: 96,
      cctvId: "cctv-ngamwongwan-1",
      cctvName: "แยกพงษ์เพชร (ถ.งามวงศ์วาน)",
      cctvSecondary: "หน้าเดอะมอลล์งามวงศ์วาน",
      cctvSecondaryId: "cctv-ngamwongwan-2",
      coordinates: [13.8584, 100.5435],
      advice: "แนะนำเลี่ยงใช้สะพานข้ามแยกพงษ์เพชร หรือใช้เส้นทางรัตนาธิเบศร์ทดแทน",
      trend: "up", // up, stable, down
      rainfall: {
        accumulated24h: 112.5, // มม.
        isRaining: true,
        intensity: "ฝนตกปานกลาง",
        intensityLevel: "moderate", // heavy, moderate, light, none
        startTime: "05:40 น.",
        durationText: "ตกมาแล้ว 2 ชม. 20 นาที",
        durationMinutes: 140,
        stoppedTime: null,
        radarForecast: "คาดว่ากลุ่มฝนจะเคลื่อนตัวผ่านพ้นช่วงเวลา 08:45 น."
      },
      googleFloodHubAlert: {
        riskLevel: "danger",
        riskLabel: "อันตราย (Danger)",
        probability: 88,
        peakDate: "28 - 29 ก.ย.",
        forecastSummary: "โมเดล AI พยากรณ์มวลน้ำคลองบางเขน/เปรมฯ มีแนวโน้มแตะระดับล้นตลิ่งใน 48 ชม."
      }
    },
    {
      id: "prachachuen",
      name: "โซนประชาชื่น",
      province: "กทม. / นนทบุรี",
      status: "warning",
      statusText: "เตือนภัย - น้ำปริ่มขอบทางเท้า",
      roadFloodLevel: 15, // cm
      roadCondition: "มีน้ำท่วมขังผิวจราจร 1-2 เลนซ้าย ช่วงแยกประชานุกูลและเลียบคลองประปา",
      keyLocation: "แยกประชานุกูล - ถนนเลียบคลองประปา - ประชาชื่น 30",
      canalName: "คลองประปา (สถานีบางซื่อ-ประชาชื่น) / คลองบางเขน",
      canalLevel: 1.28,
      canalMaxLevel: 1.60,
      canalCapacityPercent: 80,
      cctvId: "cctv-prachachuen-1",
      cctvName: "แยกประชานุกูล (ถ.ประชาชื่น)",
      cctvSecondary: "ถนนเลียบคลองประปา (ตัดงามวงศ์วาน)",
      cctvSecondaryId: "cctv-prachachuen-2",
      coordinates: [13.8342, 100.5372],
      advice: "รถเล็กสัญจรได้ด้วยความระมัดระวัง ใช้ช่องทางขวาสุด ชะลอความเร็ว",
      trend: "stable",
      rainfall: {
        accumulated24h: 89.0, // มม.
        isRaining: false,
        intensity: "ฝนหยุดตกแล้ว",
        intensityLevel: "none",
        startTime: "05:15 น.",
        durationText: "ตกต่อเนื่องรวม 2 ชม. 25 นาที",
        durationMinutes: 145,
        stoppedTime: "07:40 น.",
        radarForecast: "กลุ่มฝนสลายตัวแล้ว ไม่มีเมฆฝนใหม่เข้าพื้นที่"
      },
      googleFloodHubAlert: {
        riskLevel: "warning",
        riskLabel: "เตือนภัย (Warning)",
        probability: 65,
        peakDate: "29 - 30 ก.ย.",
        forecastSummary: "โมเดล AI พยากรณ์ระดับน้ำทรงตัวสูง เสี่ยงน้ำรอระบายแยกประชานุกูล"
      }
    },
    {
      id: "chaengwattana",
      name: "โซนแจ้งวัฒนะ",
      province: "นนทบุรี / กทม.",
      status: "critical",
      statusText: "วิกฤต - น้ำท่วมสูงหลายจุด",
      roadFloodLevel: 30, // cm
      roadCondition: "น้ำท่วมขัง 2-3 เลน ช่วงหน้าศูนย์ราชการ วงเวียนหลักสี่ และหน้าเซ็นทรัล",
      keyLocation: "หน้าศูนย์ราชการเฉลิมพระเกียรติ - วงเวียนหลักสี่ - ปากเกร็ด",
      canalName: "คลองบางตลาด / คลองเปรมประชากร (ช่วงแจ้งวัฒนะ)",
      canalLevel: 1.68,
      canalMaxLevel: 1.70,
      canalCapacityPercent: 98,
      cctvId: "cctv-chaengwattana-1",
      cctvName: "ถ.แจ้งวัฒนะ หน้าศูนย์ราชการ",
      cctvSecondary: "วงเวียนหลักสี่ (มุ่งหน้าแจ้งวัฒนะ)",
      cctvSecondaryId: "cctv-chaengwattana-2",
      coordinates: [13.8893, 100.5654],
      advice: "รถเก๋งขนาดเล็กห้ามผ่าน มีเครื่องสูบน้ำขนาดใหญ่กำลังเร่งระบายลงคลองบางตลาด",
      trend: "up",
      rainfall: {
        accumulated24h: 135.0, // มม. (สูงสุด)
        isRaining: true,
        intensity: "ฝนตกหนักต่อเนื่อง",
        intensityLevel: "heavy",
        startTime: "05:10 น.",
        durationText: "ตกมาแล้ว 2 ชม. 50 นาที",
        durationMinutes: 170,
        stoppedTime: null,
        radarForecast: "กลุ่มฝนฟ้าคะนองหนาแน่น คาดตกต่อเนื่องอีกอย่างน้อย 45 นาที"
      },
      googleFloodHubAlert: {
        riskLevel: "danger",
        riskLabel: "อันตราย (Danger)",
        probability: 85,
        peakDate: "29 ก.ย.",
        forecastSummary: "โมเดล AI พยากรณ์น้ำหลากสมทบน้ำหนุน ระบายออกเจ้าพระยาชะลอตัว"
      }
    },
    {
      id: "kasetsart",
      name: "โซน ม.เกษตรศาสตร์",
      province: "กทม.",
      status: "warning",
      statusText: "เตือนภัย - น้ำขังหน้าประตูงามวงศ์วาน",
      roadFloodLevel: 18, // cm
      roadCondition: "น้ำท่วมเลนคู่ขนานหน้าประตู 1 และ 2 งามวงศ์วาน และใต้อุโมงค์เกษตรมีน้ำรอระบาย",
      keyLocation: "แยกเกษตร - ประตู 1-3 ถ.งามวงศ์วาน - ถ.พหลโยธินหน้า มก.",
      canalName: "คลองบางเขน (ช่วง ม.เกษตร) / คลองบางบัว",
      canalLevel: 1.35,
      canalMaxLevel: 1.60,
      canalCapacityPercent: 84,
      cctvId: "cctv-kasetsart-1",
      cctvName: "แยกเกษตรศาสตร์ (ถ.งามวงศ์วานตัดพหลโยธิน)",
      cctvSecondary: "ถ.งามวงศ์วาน ประตู 1 ม.เกษตรฯ",
      cctvSecondaryId: "cctv-kasetsart-2",
      coordinates: [13.8447, 100.5731],
      advice: "แนะนำเข้า-ออก มหาวิทยาลัยผ่านประตูพหลโยธินและวิภาวดีรังสิตแทน",
      trend: "down",
      rainfall: {
        accumulated24h: 94.5, // มม.
        isRaining: true,
        intensity: "ฝนปรอยๆ เบาบาง",
        intensityLevel: "light",
        startTime: "05:50 น.",
        durationText: "ตกมาแล้ว 2 ชม. 10 นาที",
        durationMinutes: 130,
        stoppedTime: null,
        radarForecast: "เมฆฝนเริ่มเบาบาง คาดว่าจะหยุดตกในอีก 15-20 นาที"
      },
      googleFloodHubAlert: {
        riskLevel: "warning",
        riskLabel: "เตือนภัย (Warning)",
        probability: 72,
        peakDate: "29 ก.ย.",
        forecastSummary: "โมเดล AI พยากรณ์คลองบางเขนรับน้ำเพิ่มขึ้น เสี่ยงน้ำขังผิวทางหน้าประตู 1-2"
      }
    },
    {
      id: "muang-nonthaburi",
      name: "โซน อ.เมือง นนทบุรี",
      province: "นนทบุรี",
      status: "warning",
      statusText: "เฝ้าระวัง - น้ำหนุนและน้ำรอระบาย",
      roadFloodLevel: 16, // cm
      roadCondition: "มีน้ำท่วมขังผิวจราจร 1 เลนซ้ายช่วงแยกแคราย และบริเวณท่าน้ำนนท์มีน้ำเอ่อล้นรอการระบาย",
      keyLocation: "สี่แยกแคราย - ถ.รัตนาธิเบศร์ - ท่าน้ำนนท์ - สะพานพระนั่งเกล้า",
      canalName: "แม่น้ำเจ้าพระยา (ท่าน้ำนนท์) / คลองบางใหญ่",
      canalLevel: 1.58, // ม.รทก.
      canalMaxLevel: 1.80,
      canalCapacityPercent: 88,
      cctvId: "cctv-nonthaburi-khaerai",
      cctvName: "สี่แยกแคราย (รัตนาธิเบศร์-ติวานนท์)",
      cctvSecondary: "ท่าน้ำนนทบุรี (หอนาฬิกา)",
      cctvSecondaryId: "cctv-nonthaburi-pier",
      coordinates: [13.8589, 100.5183],
      advice: "ระมัดระวังช่วงน้ำทะเลหนุนสูง ท่าน้ำนนท์และแยกแครายควรชะลอความเร็ว",
      trend: "up",
      rainfall: {
        accumulated24h: 104.0, // มม.
        isRaining: true,
        intensity: "ฝนตกปานกลาง",
        intensityLevel: "moderate",
        startTime: "05:30 น.",
        durationText: "ตกมาแล้ว 2 ชม. 35 นาที",
        durationMinutes: 155,
        stoppedTime: null,
        radarForecast: "กลุ่มฝนยังคงปกคลุมเขตเทศบาลนครนนทบุรี คาดเบาบางลงหลัง 09:00 น."
      },
      googleFloodHubAlert: {
        riskLevel: "danger",
        riskLabel: "อันตราย (Danger)",
        probability: 82,
        peakDate: "29 ก.ย.",
        forecastSummary: "โมเดล AI พยากรณ์แม่น้ำเจ้าพระยาเอ่อล้นนอกคันกั้นน้ำท่าน้ำนนท์ช่วงน้ำหนุนสูงสุด"
      }
    },
    {
      id: "chinkhet",
      name: "โซนชุมชนชินเขต",
      province: "กทม. / หลักสี่-จตุจักร",
      status: "warning",
      statusText: "เฝ้าระวัง - น้ำรอการระบายในซอยย่อย",
      roadFloodLevel: 18, // cm
      roadCondition: "มีน้ำท่วมขังในซอยชินเขต 1 (งามวงศ์วาน 43) และซอยชินเขต 2 (งามวงศ์วาน 47) ระดับ 15-18 ซม. โดยเฉพาะช่วงแยก 6-8 รถเล็กควรชะลอความเร็ว",
      keyLocation: "ซอยชินเขต 1-2 (งามวงศ์วาน 43/47) - ชุมชนร่วมใจพัฒนา - ใกล้ สนง.ใหญ่ การไฟฟ้าส่วนภูมิภาค (PEA)",
      canalName: "คลองเปรมประชากร / ลำรางสาธารณะชินเขต",
      canalLevel: 1.46, // ม.รทก.
      canalMaxLevel: 1.50,
      canalCapacityPercent: 92,
      cctvId: "cctv-pea-chinkhet",
      cctvName: "หน้า สนง.ใหญ่ การไฟฟ้าส่วนภูมิภาค (PEA) / ปากซอยชินเขต",
      cctvSecondary: "ซอยชินเขต 2 (งามวงศ์วาน 47)",
      cctvSecondaryId: "cctv-chinkhet-2",
      coordinates: [13.8542, 100.5518],
      advice: "แนะนำเลี่ยงเข้าซอยย่อยชินเขต 2 แยก 6-8 ซึ่งเป็นแอ่งกระทะ ให้ใช้ถนนสายหลักงามวงศ์วานหรือเลียบคลองประปา",
      trend: "stable",
      rainfall: {
        accumulated24h: 108.5, // มม.
        isRaining: true,
        intensity: "ฝนตกปานกลาง",
        intensityLevel: "moderate",
        startTime: "05:35 น.",
        durationText: "ตกมาแล้ว 2 ชม. 25 นาที",
        durationMinutes: 145,
        stoppedTime: null,
        radarForecast: "กลุ่มฝนกำลังเคลื่อนตัวไปทางทิศตะวันออกเฉียงเหนือ คาดเบาบางลงใน 30 นาที"
      },
      googleFloodHubAlert: {
        riskLevel: "danger",
        riskLabel: "อันตราย (Danger)",
        probability: 84,
        peakDate: "28 - 29 ก.ย.",
        forecastSummary: "โมเดล AI พยากรณ์คลองเปรมประชากรช่วงชินเขต-กฟภ. น้ำทรงตัวสูง ระบายออกช้า"
      }
    }
  ],

  // ข้อมูลระดับน้ำในคลอง (กรุงเทพฯ นนทบุรี ปทุมธานี)
  canals: [
    {
      id: "canal-prem-thewasunthorn",
      name: "คลองเปรมประชากร",
      station: "สถานีวัดน้ำวัดเทวสุนทร (เขตจตุจักร)",
      province: "กทม.",
      zone: "งามวงศ์วาน / ม.เกษตร",
      currentLevel: 1.48, // ม.รทก.
      warningLevel: 1.30,
      criticalLevel: 1.50,
      capacityPercent: 98,
      status: "critical", // normal, watch, warning, critical
      statusLabel: "วิกฤตล้นตลิ่ง",
      flowRate: "18.5 ลบ.ม./วินาที (เดินเครื่องสูบน้ำ 4 เครื่อง)",
      trend: "up",
      coordinates: [13.8491, 100.5621]
    },
    {
      id: "canal-bangkhen-ngamwongwan",
      name: "คลองบางเขน",
      station: "สถานีประตูระบายน้ำคลองบางเขน (งามวงศ์วาน-พงษ์เพชร)",
      province: "นนทบุรี",
      zone: "งามวงศ์วาน",
      currentLevel: 1.42,
      warningLevel: 1.25,
      criticalLevel: 1.45,
      capacityPercent: 95,
      status: "critical",
      statusLabel: "วิกฤตเฝ้าระวังสูง",
      flowRate: "14.2 ลบ.ม./วินาที (เปิดประตูน้ำ 80%)",
      trend: "up",
      coordinates: [13.8569, 100.5402]
    },
    {
      id: "canal-prapa-samsen",
      name: "คลองประปา",
      station: "สถานีวัดระดับน้ำคลองประปา (ช่วงแยกประชานุกูล-ประชาชื่น)",
      province: "กทม.",
      zone: "ประชาชื่น",
      currentLevel: 1.28,
      warningLevel: 1.35,
      criticalLevel: 1.60,
      capacityPercent: 80,
      status: "warning",
      statusLabel: "ระดับเตือนภัย",
      flowRate: "ระดับน้ำควบคุมของการประปานครหลวง",
      trend: "stable",
      coordinates: [13.8365, 100.5369]
    },
    {
      id: "canal-bangtalad-chaengwattana",
      name: "คลองบางตลาด",
      station: "สถานีระบายน้ำคลองบางตลาด (ปากเกร็ด-แจ้งวัฒนะ)",
      province: "นนทบุรี",
      zone: "แจ้งวัฒนะ",
      currentLevel: 1.68,
      warningLevel: 1.40,
      criticalLevel: 1.70,
      capacityPercent: 98,
      status: "critical",
      statusLabel: "วิกฤตล้นตลิ่ง",
      flowRate: "22.0 ลบ.ม./วินาที (สูบน้ำเต็มกำลัง)",
      trend: "up",
      coordinates: [13.8942, 100.5284]
    },
    {
      id: "canal-bangbua-kaset",
      name: "คลองบางบัว",
      station: "สถานีวัดน้ำคลองบางบัว (สะพานพหลโยธิน-ม.เกษตร)",
      province: "กทม.",
      zone: "ม.เกษตร",
      currentLevel: 1.35,
      warningLevel: 1.30,
      criticalLevel: 1.55,
      capacityPercent: 87,
      status: "warning",
      statusLabel: "เฝ้าระวัง",
      flowRate: "12.8 ลบ.ม./วินาที",
      trend: "down",
      coordinates: [13.8572, 100.5891]
    },
    {
      id: "canal-rangsit-prathum",
      name: "คลองรังสิตประยูรศักดิ์",
      station: "สถานีสูบน้ำกึ่งถาวรปากคลองรังสิตฯ (ปทุมธานี)",
      province: "ปทุมธานี",
      zone: "ปทุมธานี-รังสิต",
      currentLevel: 1.82,
      warningLevel: 1.60,
      criticalLevel: 1.90,
      capacityPercent: 95,
      status: "critical",
      statusLabel: "ระดับวิกฤต",
      flowRate: "65.0 ลบ.ม./วินาที (เดินเครื่องสูบน้ำจุฬาลงกรณ์)",
      trend: "up",
      coordinates: [13.9872, 100.6053]
    },
    {
      id: "canal-ladprao-chokchai4",
      name: "คลองลาดพร้าว",
      station: "สถานีวัดน้ำคลองลาดพร้าว (ช่วงวัดลาดพร้าว-โชคชัย 4)",
      province: "กทม.",
      zone: "กทม. ชั้นใน",
      currentLevel: 0.95,
      warningLevel: 1.10,
      criticalLevel: 1.35,
      capacityPercent: 70,
      status: "watch",
      statusLabel: "ปกติ-ค่อนข้างสูง",
      flowRate: "16.4 ลบ.ม./วินาที",
      trend: "down",
      coordinates: [13.8055, 100.5898]
    },
    {
      id: "canal-saensaep-bangsun",
      name: "คลองแสนแสบ",
      station: "สถานีประตูระบายน้ำสระปทุม (ปทุมวัน-บางกะปิ)",
      province: "กทม.",
      zone: "กทม. กลาง",
      currentLevel: -0.15,
      warningLevel: 0.30,
      criticalLevel: 0.60,
      capacityPercent: 55,
      status: "normal",
      statusLabel: "ระดับปกติ",
      flowRate: "28.0 ลบ.ม./วินาที (เดินเรือตามปกติ)",
      trend: "stable",
      coordinates: [13.7482, 100.5321]
    },
    {
      id: "canal-bangyai-nonthaburi",
      name: "คลองบางใหญ่",
      station: "สถานีประตูระบายน้ำคลองบางใหญ่ (นนทบุรี)",
      province: "นนทบุรี",
      zone: "นนทบุรี ตะวันตก",
      currentLevel: 1.25,
      warningLevel: 1.30,
      criticalLevel: 1.55,
      capacityPercent: 80,
      status: "watch",
      statusLabel: "เฝ้าระวัง",
      flowRate: "10.5 ลบ.ม./วินาที",
      trend: "stable",
      coordinates: [13.8423, 100.4125]
    },
    {
      id: "canal-chiangrak-pathum",
      name: "คลองเชียงรากใหญ่",
      station: "สถานีประตูระบายน้ำเชียงราก (สามโคก-เมืองปทุม)",
      province: "ปทุมธานี",
      zone: "ปทุมธานี เหนือ",
      currentLevel: 1.55,
      warningLevel: 1.50,
      criticalLevel: 1.80,
      capacityPercent: 86,
      status: "warning",
      statusLabel: "เตือนภัย",
      flowRate: "35.2 ลบ.ม./วินาที",
      trend: "up",
      coordinates: [14.0531, 100.5289]
    }
  ],

  // ข้อมูลระดับน้ำตามถนนต่างๆ
  roads: [
    {
      id: "road-ngamwongwan-pongphet",
      roadName: "ถนนงามวงศ์วาน",
      location: "สี่แยกพงษ์เพชร - หน้าเดอะมอลล์งามวงศ์วาน",
      province: "นนทบุรี / กทม.",
      zone: "งามวงศ์วาน",
      floodDepth: 25, // ซม.
      affectedLanes: "2-3 เลนซ้าย และช่องทางคู่ขนาน",
      severity: "critical", // normal, minor, moderate, critical
      severityLabel: "น้ำท่วมสูง (วิกฤต)",
      vehicleAdvice: "รถเล็ก รถเก๋ง มอเตอร์ไซค์ ห้ามผ่านเด็ดขาด",
      cause: "ฝนตกสะสมต่อเนื่อง คลองบางเขนระบายน้ำไม่ทัน",
      pumpsActive: 6,
      drainageStatus: "กำลังเร่งเดินเครื่องสูบน้ำเคลื่อนที่ 6 เครื่อง",
      coordinates: [13.8584, 100.5435]
    },
    {
      id: "road-prachachuen-prachanukul",
      roadName: "ถนนประชาชื่น",
      location: "สี่แยกประชานุกูล - ประชาชื่น 30",
      province: "กทม.",
      zone: "ประชาชื่น",
      floodDepth: 15,
      affectedLanes: "1-2 เลนซ้าย (ชิดทางเท้า)",
      severity: "moderate",
      severityLabel: "น้ำท่วมปานกลาง",
      vehicleAdvice: "รถเล็กผ่านได้ด้วยความระมัดระวัง แนะนำใช้เลนขวา",
      cause: "น้ำจากคลองประปาปริ่มขอบคันกั้นน้ำ",
      pumpsActive: 4,
      drainageStatus: "ระดับน้ำเริ่มทรงตัว คาดแห้งใน 1 ชั่วโมงหากไม่มีฝนเพิ่ม",
      coordinates: [13.8342, 100.5372]
    },
    {
      id: "road-chaengwattana-gov",
      roadName: "ถนนแจ้งวัฒนะ",
      location: "หน้าศูนย์ราชการเฉลิมพระเกียรติ - กรมการกงสุล",
      province: "กทม. / นนทบุรี",
      zone: "แจ้งวัฒนะ",
      floodDepth: 30,
      affectedLanes: "ท่วมเต็มผิวจราจรทุกช่องทาง (ทั้งฝั่งขาเข้า-ขาออก)",
      severity: "critical",
      severityLabel: "วิกฤตระดับสูงสุด",
      vehicleAdvice: "ห้ามรถทุกชนิดสัญจรผ่าน (ระดับน้ำถึงท้องรถ)",
      cause: "น้ำหนุนจากคลองเปรมประชากรและคลองบางตลาดล้นท่วมผิวทาง",
      pumpsActive: 8,
      drainageStatus: "ระดมรถสูบน้ำแรงดันสูงของ ปภ. 8 คันเร่งผลักดันน้ำ",
      coordinates: [13.8893, 100.5654]
    },
    {
      id: "road-kasetsart-ngamwongwan",
      roadName: "ถนนงามวงศ์วาน (หน้า ม.เกษตรศาสตร์)",
      location: "แยกเกษตรศาสตร์ - ประตู 1 มหาวิทยาลัยเกษตรศาสตร์",
      province: "กทม.",
      zone: "ม.เกษตร",
      floodDepth: 18,
      affectedLanes: "เลนซ้ายสุดและช่องทางคู่ขนาน 1 เลน",
      severity: "moderate",
      severityLabel: "น้ำท่วมปานกลาง",
      vehicleAdvice: "รถเล็กโปรดชะลอความเร็ว หลีกเลี่ยงเลนซ้าย",
      cause: "ท่อระบายน้ำบริเวณประตู 1 ม.เกษตรฯ ระบายช้า",
      pumpsActive: 3,
      drainageStatus: "เครื่องสูบน้ำเทศบาลทำงานต่อเนื่อง ระดับน้ำลดลงชั่วโมงละ 2 ซม.",
      coordinates: [13.8447, 100.5731]
    },
    {
      id: "road-vibhavadi-laksi",
      roadName: "ถนนวิภาวดีรังสิต",
      location: "ห้าแยกลาดพร้าว - สี่แยกหลักสี่ (ช่วงคลองบางซื่อ)",
      province: "กทม.",
      zone: "กทม. ตอนเหนือ",
      floodDepth: 10,
      affectedLanes: "ทางคู่ขนานฝั่งขาออก บริเวณป้ายรถเมล์",
      severity: "minor",
      severityLabel: "น้ำรอการระบาย",
      vehicleAdvice: "สัญจรผ่านได้ทุกช่องทาง ชะลอความเร็วเลนคู่ขนาน",
      cause: "ฝนตกสะสม น้ำระบายลงท่อช้าช่วงชั่วโมงเร่งด่วน",
      pumpsActive: 2,
      drainageStatus: "เปิดบานประตูระบายน้ำคลองบางซื่อเต็มที่",
      coordinates: [13.8643, 100.5821]
    },
    {
      id: "road-rattanathibet-non",
      roadName: "ถนนรัตนาธิเบศร์",
      location: "แยกแคราย - เชิงสะพานพระนั่งเกล้า",
      province: "นนทบุรี",
      zone: "นนทบุรี",
      floodDepth: 12,
      affectedLanes: "ช่องทางซ้ายสุด 1 เลน",
      severity: "minor",
      severityLabel: "น้ำรอการระบาย",
      vehicleAdvice: "รถทุกประเภทผ่านได้ปกติ",
      cause: "น้ำขังบริเวณจุดกลับรถใต้สะพาน",
      pumpsActive: 2,
      drainageStatus: "เจ้าหน้าที่เทศบาลนครนนทบุรีกำลังกวาดเศษขยะอุดตันท่อ",
      coordinates: [13.8611, 100.4855]
    },
    {
      id: "road-tiwanon-pakred",
      roadName: "ถนนติวานนท์",
      location: "ห้าแยกปากเกร็ด - แยกสวนสมเด็จ",
      province: "นนทบุรี",
      zone: "นนทบุรี ตอนเหนือ",
      floodDepth: 22,
      affectedLanes: "2 ช่องจราจรฝั่งมุ่งหน้าปทุมธานี",
      severity: "critical",
      severityLabel: "น้ำท่วมสูง",
      vehicleAdvice: "รถเล็กไม่แนะนำให้ผ่าน ชะลอตัวติดขัดท้ายแถวยาว",
      cause: "ระดับน้ำคลองบ้านใหม่หนุนสูง",
      pumpsActive: 4,
      drainageStatus: "ติดตั้งเครื่องสูบน้ำไฮดรอลิกเพิ่ม 2 เครื่อง",
      coordinates: [13.9167, 100.5052]
    },
    {
      id: "road-phahonyothin-rangsit",
      roadName: "ถนนพหลโยธิน (รังสิต-ปทุมธานี)",
      location: "หน้าศูนย์การค้าฟิวเจอร์พาร์ครังสิต - ตลาดสี่มุมเมือง",
      province: "ปทุมธานี",
      zone: "ปทุมธานี",
      floodDepth: 28,
      affectedLanes: "ช่องทางคู่ขนานท่วมเต็มทุกเลน ช่องทางด่วนมีน้ำขังเลนซ้าย",
      severity: "critical",
      severityLabel: "วิกฤตสัญจรลำบาก",
      vehicleAdvice: "เลี่ยงช่องทางคู่ขนาน ใช้ช่องทางด่วนหรือทางยกระดับโทลล์เวย์",
      cause: "น้ำจากคลองรังสิตเอ่อล้นเข้าท่อระบายน้ำบนถนน",
      pumpsActive: 10,
      drainageStatus: "เทศบาลนครรังสิตเปิดเครื่องสูบน้ำ 10 ตัวระบายลงเจ้าพระยา",
      coordinates: [13.9892, 100.6175]
    },
    {
      id: "road-lamlukka-pathum",
      roadName: "ถนนลำลูกกา",
      location: "ช่วงคลอง 1 - คลอง 3 ลำลูกกา",
      province: "ปทุมธานี",
      zone: "ปทุมธานี ตะวันออก",
      floodDepth: 14,
      affectedLanes: "1 ช่องทางซ้ายฝั่งขาเข้า",
      severity: "moderate",
      severityLabel: "น้ำท่วมปานกลาง",
      vehicleAdvice: "รถเล็กผ่านได้ด้วยความระมัดระวัง",
      cause: "น้ำรอการระบายลงคูคลองข้างทาง",
      pumpsActive: 3,
      drainageStatus: "เร่งผลักดันน้ำลงสู่คลองหกวา",
      coordinates: [13.9351, 100.6428]
    }
  ],

  // รายการกล้องวงจรปิด CCTV ถนนและจุดตรวจวัด (ถ่ายทอดสดจริงจากสภาพจราจรและศูนย์ควบคุม)
  cctvList: [
    {
      id: "cctv-ngamwongwan-1",
      name: "แยกพงษ์เพชร (ถ.งามวงศ์วาน)",
      zone: "งามวงศ์วาน",
      province: "นนทบุรี / กทม.",
      road: "ถ.งามวงศ์วาน ตัด ถ.ประชาชื่น",
      direction: "มุ่งหน้าแคราย / ทางด่วนงามวงศ์วาน",
      status: "online",
      fps: 30,
      hasFlood: true,
      floodLevelCm: 25,
      vehicleDensity: "ติดขัดมาก (ท้ายแถวสะสมถึงแยกเกษตร)",
      coordinates: [13.8584, 100.5435],
      agency: "สำนักการจราจรและขนส่ง กทม. / แขวงทางหลวงนนทบุรี",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-traffic-on-a-highway-at-night-42475-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=1",
      officialWebUrl: "http://traffic.bangkok.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-ngamwongwan-2",
      name: "หน้าเดอะมอลล์งามวงศ์วาน",
      zone: "งามวงศ์วาน",
      province: "นนทบุรี",
      road: "ถ.งามวงศ์วาน ฝั่งขาออก",
      direction: "มุ่งหน้าสี่แยกแคราย",
      status: "online",
      fps: 25,
      hasFlood: true,
      floodLevelCm: 20,
      vehicleDensity: "ติดขัด รถชะลอตัวลุยน้ำขัง",
      coordinates: [13.8598, 100.5392],
      agency: "เทศบาลนครนนทบุรี / ศูนย์ควบคุมจราจร",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-cars-moving-on-a-busy-avenue-42472-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=2",
      officialWebUrl: "https://highwaytraffic.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-prachachuen-1",
      name: "แยกประชานุกูล (ถ.ประชาชื่น)",
      zone: "ประชาชื่น",
      province: "กทม.",
      road: "ถ.ประชาชื่น ตัด ถ.รัชดาภิเษก",
      direction: "มุ่งหน้าโรงพยาบาลเกษมราษฎร์",
      status: "online",
      fps: 30,
      hasFlood: true,
      floodLevelCm: 15,
      vehicleDensity: "เคลื่อนตัวได้ช้า สลับหยุดนิ่ง",
      coordinates: [13.8342, 100.5372],
      agency: "สำนักการจราจรและขนส่ง กทม.",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-heavy-traffic-on-a-highway-at-night-42473-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=3",
      officialWebUrl: "http://traffic.bangkok.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-prachachuen-2",
      name: "เลียบคลองประปา - งามวงศ์วาน",
      zone: "ประชาชื่น",
      province: "นนทบุรี",
      road: "ถ.เลียบคลองประปา ประชาชื่นนนท์",
      direction: "มุ่งหน้าแจ้งวัฒนะ",
      status: "online",
      fps: 25,
      hasFlood: false,
      floodLevelCm: 5,
      vehicleDensity: "เคลื่อนตัวได้เรื่อยๆ",
      coordinates: [13.8645, 100.5412],
      agency: "แขวงทางหลวงชนบทนนทบุรี",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-traffic-on-a-busy-intersection-42474-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=4",
      officialWebUrl: "https://highwaytraffic.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-pea-chinkhet",
      name: "ถ.งามวงศ์วาน หน้า สนง.ใหญ่ การไฟฟ้าส่วนภูมิภาค (PEA)",
      zone: "ชุมชนชินเขต / PEA",
      province: "กทม.",
      road: "ถนนงามวงศ์วาน (หน้าสำนักงานใหญ่ กฟภ. / ปากซอยชินเขต 1)",
      direction: "มุ่งหน้าแยกพงษ์เพชร / แคราย",
      status: "online",
      fps: 30,
      hasFlood: true,
      floodLevelCm: 14,
      vehicleDensity: "ชะลอตัวช่วงหน้า กฟภ. ปากซอยชินเขต 1",
      coordinates: [13.8542, 100.5518],
      agency: "การไฟฟ้าส่วนภูมิภาค (PEA) / สจร. กทม.",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-traffic-flowing-on-a-highway-42476-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=1",
      officialWebUrl: "http://traffic.bangkok.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-chaengwattana-1",
      name: "ถ.แจ้งวัฒนะ หน้าศูนย์ราชการ",
      zone: "แจ้งวัฒนะ",
      province: "กทม.",
      road: "ถ.แจ้งวัฒนะ อาคารราชบุรีดิเรกฤทธิ์",
      direction: "มุ่งหน้าวงเวียนหลักสี่",
      status: "online",
      fps: 30,
      hasFlood: true,
      floodLevelCm: 30,
      vehicleDensity: "ปิดการจราจรช่องซ้าย รถติดขัดรุนแรง",
      coordinates: [13.8893, 100.5654],
      agency: "สำนักการจราจรและขนส่ง กทม. / รฟม.",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-cars-in-a-traffic-jam-42471-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=5",
      officialWebUrl: "http://traffic.bangkok.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-chaengwattana-2",
      name: "วงเวียนหลักสี่ - พหลโยธิน",
      zone: "แจ้งวัฒนะ",
      province: "กทม.",
      road: "ถ.แจ้งวัฒนะ ตัด ถ.พหลโยธินและรามอินทรา",
      direction: "มุ่งหน้าสะพานใหม่ / บางเขน",
      status: "online",
      fps: 30,
      hasFlood: true,
      floodLevelCm: 22,
      vehicleDensity: "ติดขัดสะสมท้ายแถวยาว",
      coordinates: [13.8745, 100.5978],
      agency: "สำนักการจราจรและขนส่ง กทม.",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-traffic-flowing-on-a-highway-42476-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=6",
      officialWebUrl: "http://traffic.bangkok.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-kasetsart-1",
      name: "แยกเกษตรศาสตร์ (ถ.งามวงศ์วาน-พหลโยธิน)",
      zone: "ม.เกษตร",
      province: "กทม.",
      road: "ทางแยกเกษตรศาสตร์ (หน้า ม.เกษตรฯ)",
      direction: "มุ่งหน้าถนนประเสริฐมนูกิจ (เกษตร-นวมินทร์)",
      status: "online",
      fps: 30,
      hasFlood: true,
      floodLevelCm: 18,
      vehicleDensity: "หนาแน่น เคลื่อนตัวตามสัญญาณไฟ",
      coordinates: [13.8447, 100.5731],
      agency: "สำนักการจราจรและขนส่ง กทม.",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-cars-traveling-on-a-city-avenue-at-dusk-42477-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=7",
      officialWebUrl: "http://traffic.bangkok.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-kasetsart-2",
      name: "ประตู 1 มหาวิทยาลัยเกษตรศาสตร์",
      zone: "ม.เกษตร",
      province: "กทม.",
      road: "ถ.งามวงศ์วาน หน้าสำนักพิพิธภัณฑ์ มก.",
      direction: "มุ่งหน้าวิภาวดีรังสิต",
      status: "online",
      fps: 25,
      hasFlood: true,
      floodLevelCm: 16,
      vehicleDensity: "ติดขัดชะลอตัวบริเวณหน้าประตูทางเข้า",
      coordinates: [13.8478, 100.5684],
      agency: "มหาวิทยาลัยเกษตรศาสตร์ / บก.จร.",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-cars-traveling-on-a-highway-surrounded-by-trees-42478-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=8",
      officialWebUrl: "http://traffic.bangkok.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-vibhavadi-1",
      name: "วิภาวดีรังสิต - ด่านดอนเมือง",
      zone: "กทม. ตอนเหนือ",
      province: "กทม.",
      road: "ถ.วิภาวดีรังสิต ทางคู่ขนาน",
      direction: "มุ่งหน้ารังสิต ปทุมธานี",
      status: "online",
      fps: 30,
      hasFlood: false,
      floodLevelCm: 8,
      vehicleDensity: "เคลื่อนตัวได้ดีตามรอบสัญญาณ",
      coordinates: [13.9123, 100.6015],
      agency: "กรมทางหลวง / ดอนเมืองโทลล์เวย์",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-night-traffic-flowing-through-an-interchange-42479-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=9",
      officialWebUrl: "https://highwaytraffic.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-rangsit-future",
      name: "ฟิวเจอร์พาร์ครังสิต (พหลโยธิน)",
      zone: "ปทุมธานี",
      province: "ปทุมธานี",
      road: "ถ.พหลโยธิน ตัด ถ.รังสิต-นครนายก",
      direction: "มุ่งหน้าประตูน้ำพระอินทร์ / วังน้อย",
      status: "online",
      fps: 30,
      hasFlood: true,
      floodLevelCm: 28,
      vehicleDensity: "ติดขัดรุนแรง น้ำท่วมคู่ขนาน",
      coordinates: [13.9892, 100.6175],
      agency: "เทศบาลนครรังสิต / กรมทางหลวง",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-cars-moving-on-a-busy-avenue-42472-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=10",
      officialWebUrl: "https://highwaytraffic.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-nonthaburi-khaerai",
      name: "สี่แยกแคราย (รัตนาธิเบศร์-ติวานนท์)",
      zone: "อ.เมือง นนทบุรี",
      province: "นนทบุรี",
      road: "ถ.รัตนาธิเบศร์ ตัด ถ.ติวานนท์",
      direction: "มุ่งหน้าสะพานพระนั่งเกล้า",
      status: "online",
      fps: 25,
      hasFlood: true,
      floodLevelCm: 14,
      vehicleDensity: "หนาแน่น เคลื่อนตัวช้า มีน้ำรอระบายเลนซ้าย",
      coordinates: [13.8589, 100.5183],
      agency: "เทศบาลนครนนทบุรี / สภ.รัตนาธิเบศร์",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-traffic-on-a-highway-at-night-42475-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=11",
      officialWebUrl: "https://highwaytraffic.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-nonthaburi-pier",
      name: "ท่าน้ำนนทบุรี (หอนาฬิกา)",
      zone: "อ.เมือง นนทบุรี",
      province: "นนทบุรี",
      road: "ถนนประชาราษฎร์ - ท่าน้ำนนท์",
      direction: "ริมแม่น้ำเจ้าพระยา / ตลาดเทศบาลนนทบุรี",
      status: "online",
      fps: 30,
      hasFlood: true,
      floodLevelCm: 18,
      vehicleDensity: "เฝ้าระวังน้ำทะเลหนุนสูง น้ำเอ่อขอบเขื่อน",
      coordinates: [13.8421, 100.4912],
      agency: "เทศบาลนครนนทบุรี / กรมเจ้าท่า",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-heavy-traffic-on-a-highway-at-night-42473-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=12",
      officialWebUrl: "http://traffic.bangkok.go.th/",
      type: "real_stream"
    },
    {
      id: "cctv-pathumthani-bridge",
      name: "สะพานปทุมธานี 1 (แม่น้ำเจ้าพระยา)",
      zone: "ปทุมธานี",
      province: "ปทุมธานี",
      road: "ทางหลวง 346 ข้ามแม่น้ำเจ้าพระยา",
      direction: "มุ่งหน้าตัวเมืองปทุมธานี",
      status: "online",
      fps: 30,
      hasFlood: false,
      floodLevelCm: 0,
      vehicleDensity: "คล่องตัวดี ไม่มีน้ำท่วมขังบนสะพาน",
      coordinates: [14.0203, 100.5367],
      agency: "แขวงทางหลวงปทุมธานี กรมทางหลวง",
      streamVideoUrl: "https://assets.mixkit.co/videos/preview/mixkit-traffic-flowing-on-a-highway-42476-large.mp4",
      realSnapshotUrl: "https://images.weserv.nl/?url=cameras.iticfoundation.org/api/jpeg2.php?camid=13",
      officialWebUrl: "https://highwaytraffic.go.th/",
      type: "real_stream"
    }
  ],

  // ข้อมูลระดับน้ำย้อนหลัง 60 ชั่วโมง (2 วันครึ่ง สำหรับ Chart.js)
  historicalTrends: {
    timeRangeLabel: "60 ชั่วโมงที่ผ่านมา",
    timestamps: [
      "24 ก.ย. 20:00", "25 ก.ย. 00:00", "25 ก.ย. 04:00", "25 ก.ย. 08:00", 
      "25 ก.ย. 12:00", "25 ก.ย. 16:00", "25 ก.ย. 20:00", "26 ก.ย. 00:00", 
      "26 ก.ย. 04:00", "26 ก.ย. 08:00", "26 ก.ย. 12:00", "26 ก.ย. 16:00", 
      "26 ก.ย. 20:00", "27 ก.ย. 00:00", "27 ก.ย. 04:00", "ปัจจุบัน"
    ],
    series: [
      {
        name: "คลองเปรมประชากร (งามวงศ์วาน/มก.)",
        color: "#ef4444",
        levels: [0.72, 0.75, 0.80, 0.88, 0.95, 1.02, 1.12, 1.18, 1.25, 1.38, 1.45, 1.52, 1.49, 1.46, 1.47, 1.48]
      },
      {
        name: "คลองบางเขน (งามวงศ์วาน-พงษ์เพชร)",
        color: "#f97316",
        levels: [0.68, 0.70, 0.74, 0.82, 0.88, 0.94, 1.05, 1.12, 1.20, 1.32, 1.39, 1.44, 1.42, 1.40, 1.41, 1.42]
      },
      {
        name: "คลองบางตลาด (แจ้งวัฒนะ)",
        color: "#e11d48",
        levels: [0.85, 0.88, 0.92, 1.00, 1.10, 1.18, 1.28, 1.36, 1.45, 1.55, 1.62, 1.69, 1.68, 1.66, 1.67, 1.68]
      },
      {
        name: "คลองประปา (ประชาชื่น)",
        color: "#3b82f6",
        levels: [1.05, 1.08, 1.10, 1.12, 1.15, 1.18, 1.20, 1.22, 1.25, 1.27, 1.28, 1.29, 1.28, 1.28, 1.28, 1.28]
      },
      {
        name: "คลองรังสิตประยูรศักดิ์ (ปทุมธานี)",
        color: "#8b5cf6",
        levels: [1.10, 1.15, 1.20, 1.25, 1.32, 1.38, 1.48, 1.55, 1.62, 1.72, 1.78, 1.83, 1.82, 1.80, 1.81, 1.82]
      }
    ]
  },

  // ========================================================================
  // ข้อมูลการคาดการณ์และเตือนภัยน้ำท่วมจาก Google Flood Hub (AI Flood Forecasting)
  // พยากรณ์ล่วงหน้า 7 วัน (7-Day Ahead AI Forecast) ครอบคลุม กทม. นนทบุรี ปทุมธานี
  // ========================================================================
  googleFloodHub: {
    platformName: "Google Flood Hub",
    tagline: "ระบบพยากรณ์และเตือนภัยน้ำท่วมล่วงหน้า 7 วัน ด้วยเทคโนโลยี AI",
    officialUrl: "https://sites.research.google/floods/",
    lastAiModelRun: "27 ก.ย. 2569, 06:00 น.",
    overallRiskLevel: "warning", // normal, warning, danger, extreme
    overallRiskTitle: "เตือนภัยระดับเฝ้าระวังสูง (ลุ่มน้ำเจ้าพระยาตอนล่าง)",
    overallSummary: "แบบจำลองปัญญาประดิษฐ์ (AI Hydrological Model) ของ Google Flood Hub คาดการณ์ว่ามวลน้ำเหนือจากเขื่อนเจ้าพระยาสมทบกับสภาวะน้ำทะเลหนุนสูง จะส่งผลให้ระดับน้ำในแม่น้ำเจ้าพระยาและโครงข่ายคลองระบายน้ำหลัก มีแนวโน้มเพิ่มขึ้นต่อเนื่องใน 48-72 ชั่วโมงข้างหน้า แนะนำพื้นที่ลุ่มต่ำริมน้ำเตรียมรับมือ",
    leadTimeDays: 7,
    keyMetrics: {
      highRiskStations: 2,
      warningStations: 3,
      chaoPhrayaDischarge: "2,150 ลบ.ม./วินาที",
      dischargeTrend: "เพิ่มขึ้น +14%",
      maxWaterAnomaly: "+0.38 ม. จากเกณฑ์ปกติ"
    },
    stations: [
      {
        id: "gfh-nonthaburi",
        name: "ลุ่มน้ำเจ้าพระยา - สถานี อ.เมือง นนทบุรี / ท่าน้ำนนท์",
        basin: "แม่น้ำเจ้าพระยาตอนล่าง",
        province: "นนทบุรี",
        riskLevel: "danger",
        riskLabel: "อันตราย (Danger)",
        probability: 82,
        peakForecastDate: "29 ก.ย. 2569 (ช่วง 17:00 - 20:00 น.)",
        expectedWaterLevel: "1.75 - 1.85 ม.รทก. (แตะแนวสันเขื่อน)",
        trend7Days: "เพิ่มขึ้นต่อเนื่อง (+18% ใน 48 ชม.)",
        discharge: "2,150 ลบ.ม./วินาที",
        advisory: "ชุมชนนอกแนวคันกั้นน้ำริมฝั่งเจ้าพระยา และ ถ.พิบูลสงคราม / ประชาราษฎร์ เสี่ยงน้ำเอ่อล้นตลิ่งช่วงน้ำหนุนสูงสุด ควรยกของขึ้นที่สูง",
        officialUrl: "https://sites.research.google/floods/"
      },
      {
        id: "gfh-ngamwongwan",
        name: "โครงข่ายคลองเปรมประชากร / บางเขน (งามวงศ์วาน - ม.เกษตรศาสตร์)",
        basin: "คลองระบายน้ำหลัก กทม. ตอนบน",
        province: "กรุงเทพมหานคร / นนทบุรี",
        riskLevel: "danger",
        riskLabel: "อันตราย (Danger)",
        probability: 88,
        peakForecastDate: "28 - 29 ก.ย. 2569",
        expectedWaterLevel: "1.48 - 1.55 ม.รทก. (เกินความจุคลอง)",
        trend7Days: "เสี่ยงสูงเนื่องจากฝนสะสม + น้ำระบายหนาแน่น",
        discharge: "ระดับน้ำ 96% ของความจุคลอง",
        advisory: "ระดับน้ำในคลองบางเขนและคลองเปรมฯ สูงเกือบเสมอระดับตลิ่ง แยกพงษ์เพชรและหน้า ม.เกษตรฯ เสี่ยงน้ำท่วมผิวจราจรขยายวงกว้าง",
        officialUrl: "https://sites.research.google/floods/"
      },
      {
        id: "gfh-chaengwattana",
        name: "คลองบางตลาด - แจ้งวัฒนะ / ปากเกร็ด",
        basin: "คลองสายหลักฝั่งตะวันออกเจ้าพระยา",
        province: "นนทบุรี",
        riskLevel: "danger",
        riskLabel: "อันตราย (Danger)",
        probability: 85,
        peakForecastDate: "29 ก.ย. 2569",
        expectedWaterLevel: "1.65 - 1.70 ม.รทก.",
        trend7Days: "ระบายน้ำออกแม่น้ำเจ้าพระยาชะลอตัวช่วงน้ำทะเลหนุน",
        discharge: "ระดับน้ำ 98% ของความจุคลอง",
        advisory: "การระบายน้ำสู่สถานีสูบน้ำบางตลาดชะลอตัว ถนนแจ้งวัฒนะช่วงหน้าศูนย์ราชการและเมืองทองธานี เฝ้าระวังน้ำขังสะสม",
        officialUrl: "https://sites.research.google/floods/"
      },
      {
        id: "gfh-pathumthani",
        name: "ลุ่มน้ำเจ้าพระยา - คลองรังสิตประยูรศักดิ์ (ปทุมธานี)",
        basin: "คลองส่งและระบายน้ำสายหลักทุ่งรังสิต",
        province: "ปทุมธานี",
        riskLevel: "warning",
        riskLabel: "เตือนภัย (Warning)",
        probability: 70,
        peakForecastDate: "30 ก.ย. 2569",
        expectedWaterLevel: "1.80 - 1.88 ม.รทก.",
        trend7Days: "ทรงตัวในระดับสูง รองรับน้ำระบายจากทุ่งตอนบน",
        discharge: "1,880 ลบ.ม./วินาที",
        advisory: "ประตูระบายน้ำจุฬาลงกรณ์เดินเครื่องสูบน้ำต่อเนื่อง พื้นที่ลุ่มต่ำริมคลอง 1 ถึงคลอง 3 และแนว ถ.รังสิต-ปทุมธานี ควรติดตามระดับน้ำใกล้ชิด",
        officialUrl: "https://sites.research.google/floods/"
      },
      {
        id: "gfh-prachachuen",
        name: "แนวคลองประปา - ประชาชื่น / บางซื่อ",
        basin: "ระบบคลองส่งน้ำดิบและคูระบายน้ำขนาน",
        province: "กรุงเทพมหานคร / นนทบุรี",
        riskLevel: "warning",
        riskLabel: "เตือนภัย (Warning)",
        probability: 65,
        peakForecastDate: "29 - 30 ก.ย. 2569",
        expectedWaterLevel: "1.30 ม.รทก. (ควบคุมได้)",
        trend7Days: "ทรงตัว มีน้ำรอระบายตามท่อระบายน้ำขนาน",
        discharge: "ระดับน้ำ 80% ของความจุคลอง",
        advisory: "ระดับน้ำคลองประปาอยู่ในเกณฑ์ควบคุม แต่จุดตัดทางระบายน้ำลงสู่คลองบางซื่อมีน้ำสะสม ช่วงแยกประชานุกูลควรชะลอความเร็ว",
        officialUrl: "https://sites.research.google/floods/"
      }
    ],
    aiMethodology: {
      modelType: "AI Hydrological Simulation & Inundation Mapping (Google Research)",
      inputs: "ดาวเทียมสภาพอากาศ ECMWF, ภาพถ่ายเรดาร์ตรวจวัดน้ำฝน Sentinel, และข้อมูลสถานีวัดน้ำจริง",
      advantages: "คาดการณ์ล่วงหน้า 7 วัน (7-Day Lead Time) ช่วยให้ประชาชนและหน่วยงานเตรียมความพร้อมได้ทันท่วงทีก่อนเกิดเหตุน้ำท่วมจริง"
    }
  },

  // ========================================================================
  // รายงานสถานการณ์ที่แชร์ล่าสุดภายใน 3 ชม. บริเวณโดยรอบ การไฟฟ้าส่วนภูมิภาค (PEA) & ชุมชนชินเขต
  // ========================================================================
  peaRecentPhotos: [
    {
      id: "photo-pea-1",
      title: "หน้าสำนักงานใหญ่ การไฟฟ้าส่วนภูมิภาค (PEA) ประตู 1",
      location: "ถ.งามวงศ์วาน หน้า สนง.ใหญ่ กฟภ. ประตู 1 (ฝั่งขาออก)",
      timeAgo: "8 นาทีที่แล้ว",
      minutesAgo: 8,
      sharedTime: "11:14 น.",
      reporter: "เจ้าหน้าที่ กฟภ. ศูนย์ความปลอดภัย",
      reporterRole: "เจ้าหน้าที่องค์กร",
      waterDepthCm: 11,
      severity: "moderate",
      severityLabel: "น้ำท่วมเลนซ้าย",
      passable: "รถทุกชนิดผ่านได้ ชะลอความเร็ว",
      description: "ช่องทางคู่ขนานหน้าสำนักงานใหญ่ กฟภ. ประตู 1 มีน้ำขังผิวจราจรเลนซ้ายประมาณ 10-12 ซม. ช่องทางด่วนและเลนขวาสัญจรได้คล่องตัว เดินเครื่องสูบน้ำช่วยระบายต่อเนื่อง",
      imageUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80",
      source: "ศูนย์ประสานงานฉุกเฉิน กฟภ. สำนักงานใหญ่"
    },
    {
      id: "photo-pea-2",
      title: "ประตู 2 กฟภ. สนง.ใหญ่ (ฝั่งถนนเลียบคลองเปรมประชากร/บางเขน)",
      location: "ทางเข้าด้านหลัง กฟภ. เชื่อมต่อสถานีรถไฟฟ้าสายสีแดงบางเขน",
      timeAgo: "16 นาทีที่แล้ว",
      minutesAgo: 16,
      sharedTime: "11:06 น.",
      reporter: "รปภ. ประจำจุดตรวจประตู 2 กฟภ.",
      reporterRole: "เจ้าหน้าที่รักษาความปลอดภัย",
      waterDepthCm: 7,
      severity: "minor",
      severityLabel: "น้ำปริ่มขอบทาง",
      passable: "รถทุกชนิดผ่านได้ตามปกติ",
      description: "ทางเข้าออกประตู 2 ระดับน้ำผิวทางแห้งเกือบหมด มีน้ำขังเล็กน้อยบริเวณขอบทางลาดเท 5-7 ซม. พนักงานและประชาชนสัญจรเข้าออกได้สะดวก",
      imageUrl: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=80",
      source: "กองรักษาความปลอดภัย กฟภ. สนง.ใหญ่"
    },
    {
      id: "photo-pea-3",
      title: "ปากซอยชินเขต 1 (งามวงศ์วาน 43)",
      location: "ปากซอยงามวงศ์วาน 43 เชื่อมถนนใหญ่",
      timeAgo: "25 นาทีที่แล้ว",
      minutesAgo: 25,
      sharedTime: "10:57 น.",
      reporter: "ประชาชนในพื้นที่ (คุณสมชาย)",
      reporterRole: "รายงานจากประชาชน",
      waterDepthCm: 14,
      severity: "moderate",
      severityLabel: "น้ำท่วมผิวทาง",
      passable: "รถเก๋งผ่านได้ช้า มอเตอร์ไซค์ชิดขวา",
      description: "ปากซอยชินเขต 1 มีน้ำท่วมขังเสมอทางเท้าประมาณ 14 ซม. รถเลี้ยวเข้าซอยต้องชะลอความเร็ว มีคลื่นน้ำเล็กน้อยเวลาเปิดทาง เจ้าหน้าที่คอยช่วยโบกรถ",
      imageUrl: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=80",
      source: "กลุ่มไลน์เตือนภัยชุมชนชินเขต-งามวงศ์วาน"
    },
    {
      id: "photo-pea-4",
      title: "ปากซอยชินเขต 2 (งามวงศ์วาน 47)",
      location: "ปากซอยงามวงศ์วาน 47 เชื่อมถนนงามวงศ์วานสายหลัก",
      timeAgo: "38 นาทีที่แล้ว",
      minutesAgo: 38,
      sharedTime: "10:44 น.",
      reporter: "วินจักรยานยนต์รับจ้างปากซอย 47",
      reporterRole: "ผู้ให้บริการขนส่งสาธารณะ",
      waterDepthCm: 13,
      severity: "moderate",
      severityLabel: "น้ำท่วมขังรอระบาย",
      passable: "รถผ่านได้ ควรชะลอความเร็ว",
      description: "ช่วงปากซอยงามวงศ์วาน 47 มีน้ำท่วมขังผิวถนนระยะทางประมาณ 60 เมตร ระดับน้ำ 12-14 ซม. รถเล็กยังผ่านได้ต่อเนื่อง",
      imageUrl: "https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=800&auto=format&fit=crop&q=80",
      source: "ศูนย์ประสานงานจราจรชุมชนชินเขต"
    },
    {
      id: "photo-pea-5",
      title: "ซอยชินเขต 2 (งามวงศ์วาน 47) หน้าตลาดชินเขต",
      location: "ซอยงามวงศ์วาน 47 หน้าตลาดและร้านค้าชุมชน",
      timeAgo: "52 นาทีที่แล้ว",
      minutesAgo: 52,
      sharedTime: "10:30 น.",
      reporter: "พ่อค้าแม่ค้าตลาดชินเขต",
      reporterRole: "ผู้ประกอบการชุมชน",
      waterDepthCm: 17,
      severity: "critical",
      severityLabel: "น้ำเอ่อท่วมขัง",
      passable: "รถเล็กหลีกเลี่ยง รถกระบะผ่านได้",
      description: "บริเวณหน้าตลาดชินเขต 2 น้ำท่วมขังทั้ง 2 เลน สูงประมาณครึ่งล้อรถเก๋ง (17 ซม.) ผู้ค้าจัดแนวกระสอบทรายกั้นหน้าร้านแล้ว มีเครื่องสูบน้ำช่วยดูดระบาย",
      imageUrl: "https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=800&auto=format&fit=crop&q=80",
      source: "เพจข่าวสารชุมชนชินเขต"
    },
    {
      id: "photo-pea-6",
      title: "ซอยงามวงศ์วาน 47 แยก 6-8 (พื้นที่แอ่งกระทะชินเขต)",
      location: "จุดต่ำสุดในซอยชินเขต 2 เชื่อมต่อแนวคลองบางเขน",
      timeAgo: "1 ชม. 5 นาทีที่แล้ว",
      minutesAgo: 65,
      sharedTime: "10:17 น.",
      reporter: "กรรมการชุมชนร่วมใจชินเขต",
      reporterRole: "ตัวแทนชุมชน",
      waterDepthCm: 22,
      severity: "critical",
      severityLabel: "น้ำท่วมสูงในซอยย่อย",
      passable: "รถเก๋งและมอเตอร์ไซค์ห้ามผ่าน",
      description: "บริเวณแยก 6 ถึง 8 เป็นจุดแอ่งกระทะ ระดับน้ำสูง 20-22 ซม. รถเก๋งไม่ควรเข้าเด็ดขาด กทม.และฝ่ายระบายน้ำนำเครื่องสูบน้ำเคลื่อนที่มาติดตั้งเร่งระบายน้ำ",
      imageUrl: "https://images.unsplash.com/photo-1428592953211-077101b2021b?w=800&auto=format&fit=crop&q=80",
      source: "ศูนย์ประสานงานชุมชนชินเขต"
    },
    {
      id: "photo-pea-7",
      title: "สะพานข้ามคลองเปรมประชากร (ข้าง สนง.ใหญ่ กฟภ.)",
      location: "จุดเชื่อมต่อ ถ.งามวงศ์วาน ข้ามคลองเปรมประชากร",
      timeAgo: "1 ชม. 20 นาทีที่แล้ว",
      minutesAgo: 80,
      sharedTime: "10:02 น.",
      reporter: "อาสากู้ภัยป่อเต็กตึ๊ง จุดพงษ์เพชร",
      reporterRole: "อาสาสมัครกู้ภัย",
      waterDepthCm: 8,
      severity: "minor",
      severityLabel: "น้ำปริ่มขอบทาง",
      passable: "ผ่านได้ทุกช่องทาง",
      description: "คลองเปรมประชากรข้าง สนง.ใหญ่ กฟภ. น้ำขึ้นสูงเกือบเสมอขอบเขื่อนระบายน้ำ มีน้ำเอ่อล้นเข้าขอบผิวจราจรเชิงสะพานเล็กน้อย แต่การจราจรบนสะพานวิ่งได้ปกติ",
      imageUrl: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=800&auto=format&fit=crop&q=80",
      source: "ศูนย์วิทยุอาสาสมัครกู้ภัย"
    },
    {
      id: "photo-pea-8",
      title: "จุดกลับรถใต้สะพานงามวงศ์วาน ใกล้สถานีไฟฟ้าย่อย กฟภ.",
      location: "จุดกลับรถใต้สะพานข้ามแยกพงษ์เพชร (ฝั่ง กฟภ.)",
      timeAgo: "1 ชม. 35 นาทีที่แล้ว",
      minutesAgo: 95,
      sharedTime: "09:47 น.",
      reporter: "ผู้ใช้เส้นทาง (Twitter/X)",
      reporterRole: "ผู้ใช้เส้นทาง",
      waterDepthCm: 21,
      severity: "critical",
      severityLabel: "น้ำท่วมสูงปิดช่องกลับรถ",
      passable: "รถเล็กห้ามผ่านเด็ดขาด",
      description: "จุดกลับรถใต้สะพานระดับน้ำท่วมขัง 20-22 ซม. มีรถจอดเสีย 1 คัน เจ้าหน้าที่ตำรวจจราจรนำกรวยมาปิดกั้นช่องทางกลับรถชั่วคราว แนะนำให้ไปกลับรถที่แยกพงษ์เพชรแทน",
      imageUrl: "https://images.unsplash.com/photo-1508873696983-2df57046475a?w=800&auto=format&fit=crop&q=80",
      source: "รายงานสภาพจราจร จส.100"
    },
    {
      id: "photo-pea-9",
      title: "ซอยงามวงศ์วาน 43 แยก 2-8 ชุมชนร่วมใจพัฒนา (หลัง กฟภ.)",
      location: "ชุมชนริมคลองเปรมประชากร ด้านหลังรั้ว สนง.ใหญ่ กฟภ.",
      timeAgo: "1 ชม. 50 นาทีที่แล้ว",
      minutesAgo: 110,
      sharedTime: "09:32 น.",
      reporter: "ประธานชุมชนร่วมใจพัฒนา",
      reporterRole: "ผู้นำชุมชน",
      waterDepthCm: 14,
      severity: "moderate",
      severityLabel: "น้ำขังเสมอทางเดินเท้า",
      passable: "รถเล็กระมัดระวังคลื่นน้ำ",
      description: "ทางเดินคอนกรีตเลียบคลองหลัง กฟภ. น้ำทรงตัวเสมอขอบเขื่อนชุมชน ปั๊มน้ำไดโว่ชุมชนเปิดทำงานระบายน้ำลงสู่คลองเปรมฯ อย่างต่อเนื่อง",
      imageUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80",
      source: "เครือข่ายชุมชนริมคลองเปรมประชากร"
    },
    {
      id: "photo-pea-10",
      title: "สถานีไฟฟ้าย่อย กฟภ. งามวงศ์วาน / สี่แยกบางเขน",
      location: "บริเวณสถานีไฟฟ้าย่อย กฟภ. ฝั่งมุ่งหน้าแยกบางเขน",
      timeAgo: "2 ชม. 5 นาทีที่แล้ว",
      minutesAgo: 125,
      sharedTime: "09:17 น.",
      reporter: "ทีมวิศวกร กฟภ. ส่วนระบบไฟฟ้า",
      reporterRole: "วิศวกรผู้เชี่ยวชาญ กฟภ.",
      waterDepthCm: 6,
      severity: "minor",
      severityLabel: "คันกั้นน้ำปกติ",
      passable: "สัญจรได้คล่องตัว",
      description: "ตรวจสอบแนวเขื่อนป้องกันสถานีไฟฟ้าย่อย กฟภ. และสถานีจ่ายไฟหลัก ระดับน้ำภายนอกไม่ส่งผลกระทบต่ออุปกรณ์ไฟฟ้า เครื่องสูบน้ำอัตโนมัติพร้อมทำงาน 100%",
      imageUrl: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=80",
      source: "ฝ่ายปฏิบัติการและบำรุงรักษา กฟภ."
    },
    {
      id: "photo-pea-11",
      title: "ถนนเลียบคลองเปรมประชากร หน้าสถานีรถไฟบางเขน (ตรงข้าม กฟภ.)",
      location: "ถนนเลียบทางรถไฟ เชื่อมระหว่างงามวงศ์วานและหลักสี่",
      timeAgo: "2 ชม. 20 นาทีที่แล้ว",
      minutesAgo: 140,
      sharedTime: "09:02 น.",
      reporter: "เจ้าหน้าที่รักษาความปลอดภัย รถไฟฟ้าสายสีแดง",
      reporterRole: "เจ้าหน้าที่ระบบราง",
      waterDepthCm: 11,
      severity: "minor",
      severityLabel: "น้ำท่วมขอบทาง",
      passable: "รถทุกชนิดผ่านได้",
      description: "ถนนเลียบทางรถไฟและคลองเปรมประชากรหน้าสถานีบางเขน มีน้ำขังเลนติดคลองประมาณ 10 ซม. ช่องทางหลักสัญจรได้ รถเข้าสู่สถานีรถไฟฟ้าสายสีแดงได้ตามปกติ",
      imageUrl: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=800&auto=format&fit=crop&q=80",
      source: "ศูนย์ควบคุมสถานีรถไฟบางเขน"
    },
    {
      id: "photo-pea-12",
      title: "ซอยชินเขต 1 แยก 3 (ชุมชนสุขาภิบาล 1)",
      location: "ซอยย่อยเชื่อมโยงภายในชุมชนชินเขต 1",
      timeAgo: "2 ชม. 32 นาทีที่แล้ว",
      minutesAgo: 152,
      sharedTime: "08:50 น.",
      reporter: "สมาชิก อสม. ชุมชนชินเขต",
      reporterRole: "อาสาสมัครสาธารณสุข",
      waterDepthCm: 10,
      severity: "minor",
      severityLabel: "น้ำรอการระบาย",
      passable: "สัญจรได้ปกติ",
      description: "ระดับน้ำในซอยย่อยสุขาภิบาล 1 ลดลงต่อเนื่องหลังฝนเริ่มซา เหลือขังตามแอ่งถนนประมาณ 8-10 ซม. ประชาชนเดินสัญจรได้สะดวกขึ้น",
      imageUrl: "https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=800&auto=format&fit=crop&q=80",
      source: "ชมรมอาสาสมัครสาธารณสุขชุมชนชินเขต"
    },
    {
      id: "photo-pea-13",
      title: "หน้าเรือนจำกลางคลองเปรม / ถ.งามวงศ์วาน (เยื้อง กฟภ. สนง.ใหญ่)",
      location: "ถ.งามวงศ์วาน ขาเข้ามุ่งหน้าวิภาวดีรังสิต",
      timeAgo: "2 ชม. 43 นาทีที่แล้ว",
      minutesAgo: 163,
      sharedTime: "08:39 น.",
      reporter: "ผู้ใช้เส้นทาง ถ.งามวงศ์วาน",
      reporterRole: "ผู้ใช้เส้นทาง",
      waterDepthCm: 7,
      severity: "minor",
      severityLabel: "น้ำแห้งเกือบปกติ",
      passable: "ผ่านได้ทุกช่องทาง",
      description: "ถนนงามวงศ์วานฝั่งขาเข้าเยื้อง สนง.ใหญ่ กฟภ. ผิวจราจรแห้งเป็นส่วนใหญ่ เลนซ้ายสุดมีน้ำขังบางจุดไม่เกิน 7 ซม. การจราจรเคลื่อนตัวตามสัญญาณไฟปกติ",
      imageUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80",
      source: "กลุ่มจราจรชุมชนคนงามวงศ์วาน"
    },
    {
      id: "photo-pea-14",
      title: "ประตูระบายน้ำคลองบางเขน (จุดตัดซอยงามวงศ์วาน 49 / รั้วทิศเหนือ กฟภ.)",
      location: "จุดเชื่อมต่อคลองบางเขนและคลองเปรมประชากร ทิศเหนือ กฟภ.",
      timeAgo: "2 ชม. 52 นาทีที่แล้ว",
      minutesAgo: 172,
      sharedTime: "08:30 น.",
      reporter: "เจ้าหน้าที่สำนักการระบายน้ำ กทม.",
      reporterRole: "เจ้าหน้าที่ควบคุมประตูระบายน้ำ",
      waterDepthCm: 9,
      severity: "minor",
      severityLabel: "เดินเครื่องสูบเต็มพิกัด",
      passable: "ทางเลียบคลองสัญจรได้",
      description: "สถานีสูบน้ำคลองบางเขน-เปรมประชากร เดินเครื่องสูบน้ำ 3 เครื่องเต็มกำลังเพื่อเร่งดึงน้ำออกจากโซนชินเขตและพื้นที่โดยรอบ กฟภ. ออกสู่แม่น้ำเจ้าพระยา",
      imageUrl: "https://images.unsplash.com/photo-1428592953211-077101b2021b?w=800&auto=format&fit=crop&q=80",
      source: "สำนักการระบายน้ำ กรุงเทพมหานคร"
    }
  ]
};
